### PR TITLE
Add user detector

### PR DESCRIPTION
**Pull request by zepfietje**
This PR adds a detector to get the locale from the currently authenticated user, if any.

### CODE REVIEW

**Comment by ivanvermeyen** [comment]
Thanks for your contribution!

Before merging I'd like to make sure we support this Laravel feature:
https://github.com/laravel/framework/pull/44283

Perhaps the attribute can be null by default?

**Comment by zepfietje** [comment]
Hmm I'm not sure how we should handle that.
Could you explain your suggestion?

**Comment by ivanvermeyen** [comment]
I was thinking if this is null in the config by default:

```
'user-attribute' => null,
```

Then we can check for it to avoid the MissingAttributeException:

```php
 if ($attribute === null || $user === null) {
    return null;
}
```

**Comment by zepfietje** [comment]
Isn't it clearer then to not include the detector in the default array?

**Comment by ivanvermeyen** [comment]
Yeah, I understand.

Another option is perhaps to check if the attribute exists?
Then it can be default and yet not mandatory?

**Comment by ivanvermeyen** [comment]
Unfortunately Laravel has no `hasAttribute()` method.
But I think we can do something like this:

```php
if ( ! in_array($attribute, $user->getAttributes())) {
    return null;
}
```

**Comment by zepfietje** [comment]
Yeah that should work.
Doesn't it have any performance implications though, for example calling all casts?

**Comment by zepfietje** [comment]
@ivanvermeyen, we might use `$user->getAttributeValue()` to prevent the `MissingAttributeException`?

**Comment by zepfietje** [comment]
This PR should be ready now, @ivanvermeyen.

**Comment by ivanvermeyen** [comment]
`getAttributeValue()` seems to defer to `getAttributes()`.

https://github.com/laravel/framework/blob/15f419f751474262f3ced85ea4ccce18cbcdae8e/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L481-L495

I'm not sure how big of an impact this has on performance, like you stated.
There doesn't seem to be an easy way to check the `$attributes` property without triggering the exception.

**Comment by zepfietje** [comment]
Casting only seems to happen for the specific attribute you're accessing.
So performance-wise I don't think this is an issue really.

**Comment by zepfietje** [comment]
Okay, this isn't any less performant than magically accessing properties like `$user->locale`, as it all uses the same `getAttribute()` and thus `getAttributeValue()` methods under the hood.

**Comment by ivanvermeyen** [comment]
Great, thanks for putting this together 👍 
I'll merge and tag a release.

**Comment by zepfietje** [comment]
Thanks a lot for being so swift and maintaining these awesome packages!

**Pull request merged**
